catalog/catalog_app/config/routes.rb
TestRailsApp::Application.routes.draw do

	get "profile/profile"

	match "/profile" => "profile#profile", via: [:get]

	match "/entities" => "entities#index", via: [:get], format: :xml
	match "/entities/:id" => "entities#show", via: [:get], format: :xml

	match "/entities/:entity_id/feeds" => "feeds#index", via: [:get], format: :xml

	match "/feeds/:id" => "feeds#index", via: [:get], format: :xml

	match "/monitors/:id" => "monitor_nodes#edit", via: [:put]
	match "/monitors/:id" => "monitor_nodes#show", via: [:get], format: :xml
	match "/monitors" => "monitor_nodes#create", via: [:post]
	match "/monitors" => "monitor_nodes#index", via: [:get], format: :xml

	match "/" => "root#show", format: :xml

	match "/root" => "root#show"
	match 'http_test/test' => 'http_test#test', via: [:get, :post, :put, :delete]

	resources :feeds ,format: :xml
	resources :metrics, format: :xml

	resources :entities, format: :xml do
		resources :feeds, format: :xml, via: [:get], only: [:index]
	end

	resources :monitor_nodes,  as: "monitors", path: "monitors", format: :xml

	match "*foo"  => "error#error", format: :xml

end

catalog/catalog_app/app/models/feed.rb
class Feed < ActiveRecord::Base

	attr_accessible :avg_period, :available_measurements, :measurement_url, :feed_type, :monitor_feed_url, :username, :access

	has_many :feed_parts, foreign_key: "custom_feed_id", class_name: "FeedPart"
	has_many :simple_feeds, through: :feed_parts

	belongs_to :entity
	belongs_to :metric

	attr_accessor :non_persistent_subfeeds_urls

	def monitor_node
		entity.monitor_node
	end

	PUBLIC = 1
	SIMPLE = 0

	@@FEED_TYPE_TO_INT = {"SIMPLE" => 0, "AVG" => 1, "LIST" => 2}
	@@FEED_TYPE_TO_STRING = ["SIMPLE", "AVG", "LIST"]

	@@ACCESS_TO_INT = {"PRIVATE" => 0, "PUBLIC" => 1}
	@@ACCESS_TO_STRING = ["PRIVATE", "PUBLIC"]

	'' '@param data: {"href"=>"www.monitor.com/feeds/11/",
            "type"=>"SIMPLE",
            "metric"=>{"name"=>"cpu_usage", "unit"=>"%"},
            "available_measurements"=>"2",
            "measurement"=>{"href"=>"www.monitor.com/feeds/1/measurement"}}' ''

	def self.new_from_hash(data)
		Feed.new.tap do |f|
			f.monitor_feed_url= data[:href]
			f.feed_type = get_model_feed_type(data[:type])
			f.measurement_url=data[:measurements][:href]
			f.available_measurements=data[:available_measurements].to_i
			f.non_persistent_subfeeds_urls = []
			if f.feed_type == 0
				handle_simple(data, f)
			elsif f.feed_type == 1
				handle_avg(data, f)
			elsif f.feed_type == 2
				handle_list(data, f)
			end
		end
	end


	def self.handle_simple(data, feed)
		feed.metric = Metric.get_or_create(data[:metric])
	end

	def self.handle_avg(data, feed)
		feed.access=get_model_access(data[:access])
		feed.username=data[:username]

		feed.avg_period=data[:avg_period].to_i
	end

	def self.handle_list(data, feed)
		feed.access=get_model_access(data[:access])
		feed.username=data[:username]

		#hash_subfeeds = data[:feed]
		#if (hash_subfeeds.class != Array)
		#	hash_subfeeds = [data[:feed]]
		#end
		#
		#hash_subfeeds.each do |hash_f|
		#	subfeed_url = hash_f[:href]
		#	feed.non_persistent_subfeeds_urls << subfeed_url
		#end
	end


	def self.get_model_access(type)
		@@ACCESS_TO_INT[type.upcase]
	end

	def self.get_string_access(type)
		@@ACCESS_TO_STRING[type]
	end

	def self.get_model_feed_type(type)
		@@FEED_TYPE_TO_INT[type.upcase]
	end

	def self.get_string_feed_type(type)
		@@FEED_TYPE_TO_STRING[type]
	end


	def populate_with_subfeeds
		p Feed.get_string_feed_type(feed_type)

		@non_persistent_subfeeds_urls.each do |url|
			simple_feed = Feed.where(:monitor_feed_url => url)
			simple_feeds<<simple_feed
		end
	end

	def type
		Feed.get_string_feed_type(feed_type)
	end
end

catalog/catalog_app/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

	def index

		if params[:id]
			feed = Feed.find_by_id(params[:id])
			@feeds = []
			@feeds << feed if !feed.nil? && (feed.feed_type == Feed::SIMPLE || feed.access == Feed::PUBLIC || feed.username == current_user)
		else
			metric_name=params[:metric_name]
			metric_unit=params[:metric_unit]
			entity_name=params[:entity_name]
			entity_id = params[:entity_id]


			search = Feed.scoped

			search = search.where("username = ? or access = ? or feed_type = ?", current_user, Feed::PUBLIC, Feed::SIMPLE)

			if (!metric_name.blank?)
				search = search.joins(:metric).where(metrics: {name: metric_name})
			end

			if (!metric_unit.blank?)
				search = search.joins(:metric).where(metrics: {unit: metric_unit})
			end

			if (!entity_name.blank?)
				search = search.joins(:entity).where(entities: {name: entity_name})
			end

			if(entity_id)
				search = search.joins(:entity).where(entities: {id: entity_id})
			end

			@feeds = search
		end

		#respond_to do |format|
		#	format.xml
		#end
	end


end

catalog/catalog_app/app/helpers/feeds_helper.rb
module FeedsHelper
end

catalog/catalog_app/app/views/feeds/index.xml.erb
<feeds href="<%= feeds_url%>">
    <query href="<%= feeds_url.to_s + raw("?entity_name={}&metric_name={}&metric_unit={}")%>"/>
<% @feeds.each do |f| %>
	<feed href="<%= f.monitor_feed_url %>" type="<%= f.type %>" id="<%= f.id %>" monitor_id="<%= f.entity.monitor_node.id %>">
		<entity id="<%=f.entity.id%>" href="<%= entity_url(f.entity) %>"/>
        <% if f.feed_type == 0 %>
         	<metric>
        		<name><%= f.metric.name %></name>
        		<unit><%= f.metric.unit %></unit>
        	</metric>
        	<available_measurements><%= f.available_measurements %></available_measurements>
        	<measurement href="<%= f.measurement_url %>"/>
        <% elsif f.feed_type == 1 %>
        	<available_measurements><%= f.available_measurements %></available_measurements>
        	<measurement href="<%= f.measurement_url %>"/>
        	<avg_period><%= f.avg_period %></avg_period>
    		<measure_interval><%= f.measure_interval %></measure_interval>
        <% elsif f.feed_type == 2 %>
        	<available_measurements><%= f.available_measurements %></available_measurements>
        	<measurement href="<%= f.measurement_url %>"/>
        	<% f.simple_feeds.each do |sf| %>
        		<feed href="<%= sf.monitor_feed_url %>">
		        	<metric>
		        		<name><%= sf.metric.name %></name>
		        		<unit><%= sf.metric.unit %></unit>
		        	</metric>
		        	<available_measurements><%= sf.available_measurements %></available_measurements>
	        		<measurement href="<%= sf.measurement_url %>"/>
	        	</feed>
        	 <% end %>
        <% end %>
	</feed>
<% end %>
</feeds>